### ISSUE TITLE
AC60 no output power control

### ISSUE THREAD

**Issue by homesec24** [Patrick762/hassio-bluetti-bt#22]
Thank you for this great integration!

Ich would like to control the DC output on my AC60 but i can´t get control of it.
Maybe i´m doing something wrong, but i don´t think so ;)

Can you help?

Best regards, Ralf

**Comment by Patrick762** [comment]
If I'm reading [this issue](https://github.com/warhammerkid/bluetti_mqtt/issues/74) correctly, it is not supported yet in bluetti_mqtt which is the base for this integration.
But there seems to be a [Pull Request](https://github.com/warhammerkid/bluetti_mqtt/pull/79) for the controls.
Since I do not own the AC60, I can not integrate it before this PR is merged.
